import numpy as np
import torch
from pathlib import Path
import scipy.io as io
import matplotlib.pyplot as plt

from model import AE2d


def load_ae(base_dir: Path, view: int, device: str) -> AE2d:
    sampling_config = [[2, 2], [3, 2], [5, 5], [5, 5]]
    ckpt = base_dir / "models" / f"AE_carl_view{view}_del0.1_fold0_ep100.pth"
    net = AE2d(in_channels=1, n_feat=64, sampling_config=sampling_config).to(device)
    state = torch.load(str(ckpt), map_location=device)
    net.load_state_dict(state)
    net.eval()
    return net


def decode_to_image(ae: AE2d, latent_512: np.ndarray, device: str) -> np.ndarray:
    z = torch.tensor(latent_512, dtype=torch.float32, device=device).reshape(1, 512, 1, 1)
    with torch.no_grad():
        x_rec = ae.forward_x_rec(z)
    img = x_rec[:, :, 2:-3, :].squeeze().cpu().numpy()
    return img


def run_example_test():
    base_dir = Path(__file__).resolve().parent
    device = "cpu"
    view = 0
    pairedrate = 0.1
    fold = 0
    sample_idx = 0

    ae_ckpt = base_dir / "models" / f"AE_carl_view{view}_del0.1_fold0_ep100.pth"
    ddpm_latent_path = base_dir / "data" / "ddpm_carl_view0_pairedrate0.1_fold0.npy"
    ae0 = load_ae(base_dir, view=0, device=device)
    ae1 = load_ae(base_dir, view=1, device=device)
    ae2 = load_ae(base_dir, view=2, device=device)

    # Use one latent sample generated by pretrained DDPM output.
    latent_all = np.load(str(ddpm_latent_path))
    if latent_all.ndim != 3:
        raise ValueError(f"Unexpected latent shape: {latent_all.shape}. Expected 3 dims [N, 1, D].")

    if sample_idx >= latent_all.shape[0]:
        raise ValueError(f"sample_idx {sample_idx} is out of range for generated latents of size {latent_all.shape[0]}.")

    # Recover original target latent and conditions using the same test split rule as datasets.py.
    folds = io.loadmat(str(base_dir / "data" / f"carl_del_{pairedrate}.mat"))["folds"]
    mask = folds[0, fold].astype(np.int64)
    ind_test = mask[:, view] == 0
    test_indices = np.where(ind_test)[0]
    global_idx = int(test_indices[sample_idx])

    x0 = np.load(str(base_dir / "data" / f"AE_carl_view0_del{pairedrate}_fold{fold}.npy"))
    x1 = np.load(str(base_dir / "data" / f"AE_carl_view1_del{pairedrate}_fold{fold}.npy"))
    x2 = np.load(str(base_dir / "data" / f"AE_carl_view2_del{pairedrate}_fold{fold}.npy"))

    original_latent = x0[global_idx]
    generated_latent = latent_all[sample_idx, 0, :]

    cond1_available = int(mask[global_idx, 1])
    cond2_available = int(mask[global_idx, 2])
    cond1_latent = x1[global_idx] * cond1_available
    cond2_latent = x2[global_idx] * cond2_available

    generated_img = decode_to_image(ae0, generated_latent, device=device)
    original_img = decode_to_image(ae0, original_latent, device=device)

    cond1_img = decode_to_image(ae1, cond1_latent, device=device) if cond1_available else np.zeros_like(original_img)
    cond2_img = decode_to_image(ae2, cond2_latent, device=device) if cond2_available else np.zeros_like(original_img)
    condition_img = np.concatenate([cond1_img, cond2_img], axis=1)

    out_path = base_dir / "data" / "example_recon_view0.npy"
    np.save(str(out_path), generated_img[None, None, :, :])

    fig_path = base_dir / "data" / "example_triplet_view0.png"
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))

    axes[0].imshow(generated_img, cmap="gray", vmin=0.0, vmax=1.0)
    axes[0].set_title("Generated (View 0)")
    axes[0].axis("off")

    axes[1].imshow(original_img, cmap="gray", vmin=0.0, vmax=1.0)
    axes[1].set_title("Original Target (View 0)")
    axes[1].axis("off")

    axes[2].imshow(condition_img, cmap="gray", vmin=0.0, vmax=1.0)
    axes[2].set_title(f"Condition Used (V1 avail={cond1_available}, V2 avail={cond2_available})")
    axes[2].axis("off")

    plt.tight_layout()
    fig.savefig(str(fig_path), dpi=180)
    plt.close(fig)

    print("ae_checkpoint:", str(ae_ckpt))
    print("ddpm_latent_input:", str(ddpm_latent_path))
    print("sample_idx:", sample_idx)
    print("global_dataset_idx:", global_idx)
    print("generated_shape:", tuple(generated_img.shape))
    print("original_shape:", tuple(original_img.shape))
    print("condition_shape:", tuple(condition_img.shape))
    print("recon_min:", float(generated_img.min()))
    print("recon_max:", float(generated_img.max()))
    print("recon_mean:", float(generated_img.mean()))
    print("saved_reconstruction:", str(out_path))
    print("saved_plot:", str(fig_path))


if __name__ == "__main__":
    run_example_test()
